[package]
name = "doint"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.12", features = ["mysql"] }
poise = "0.6.1"

[workspace.lints.clippy]
all = "warn" # Warn for all default Clippy lints
pedantic = "warn" # Warn for all pedantic lints (can be noisy)