[package]
name = "doint"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.12", features = ["mysql", "mysql_backend", "r2d2"] }
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.28"
poise = "0.6.1"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread"] }
