name: rust

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master

jobs:
  checks:
    name: Code Checks (fmt & clippy)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-stable"
          shared-key: "checks"

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Install sarif-fmt & clippy-sarif
        uses: taiki-e/install-action@v2
        with:
          tool: sarif-fmt, clippy-sarif

      - name: Run clippy and generate SARIF
        run: cargo clippy --message-format=json --all-targets | clippy-sarif | tee results.sarif | sarif-fmt

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    permissions:
      contents: read
      actions: read
      checks: write
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: mysql://root:@127.0.0.1:3306/test
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-stable"
          shared-key: "tests"
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Compile and Run tests
        run: cargo nextest run --no-fail-fast --failure-output final -j num-cpus --final-status-level all
  build:
    name: Build ${{ matrix.platform.os_name }} [rust ${{ matrix.toolchain }}]
    runs-on: ${{ matrix.platform.os }}
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    needs: [checks, tests]
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup ${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.platform.target }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-${{ matrix.toolchain }}"
          shared-key: "build-${{ matrix.platform.target }}"
      - name: Build
        run: cargo build --target ${{ matrix.platform.target }}
